<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="Administration module login form" />
			{widget css 'layout/login.css', 'jquery.ui.css'}
			{widget js 'LiveFormValidation.js'}
		<title>Admin - {_"Login"}</title>
	</head>
  <body>
	<div id="login-form" class="ui-corner-all">
		<p class="ui-corner-all">Mokuji CMS</p>
		<p>{_'Please login'}</p>
		{foreach $flashes as $flash}
			<div class="flash {$flash->type}">{$flash->message}</div>
		{/foreach}
	{widget formLogin}
	</div>
  </body>
</html>