<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
	<head profile="http://gmpg.org/xfn/11">
		{block #css}
            <link rel="stylesheet" type="text/css" href="{$basePath}/css/layout.css"/>
		    <link rel="stylesheet" type="text/css" href="{$basePath}/css/style.css"/>
		{/block}
		{block #js}
            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
            <script type="text/javascript" src="/js/widgets/jquery.easing.1.3.js"></script>
            <script type="text/javascript" src="/js/widgets/menu.js"></script>                                      
		{/block}
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        {keywords}
        {description}
		<title>{if isset($pagetitle)}{$pagetitle}{/if}{if (isset($pagetitle) and $pagetitle != '') and (isset($title) and $title != '')}-{/if}{if isset($title)}{$title}{/if}
        </title>
		<link rel="EditURI" type="application/rsd+xml" title="RSD" href="{link :Admin:publish:}?rsd" />
		<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{link :Admin:publish:}?wlw" />
	</head>

<body>
<div id="wrapper">
  <div id="header">
    <a href="{link Homepage:homepage}"><div class="logo">
      <h1>Martin Bažík</h1>
      <p>{_'Freelance webdeveloper'|upper}</p>
    </div></a>
    <div class="nav">
         {menu 'navigation'}
    </div>
  </div>
  <!-- header starts here -->
  <!-- container top bg starts here -->
  <div id="containertopbg">
    <!-- container bottom bg starts here -->
    <div id="containerbottombg">
      <!-- container holder starts here -->
      <div id="container">
      {include #content} 
      </div>
      <!-- container holder ends here -->
    </div>
    <!-- container bottom bg ends here -->
  </div>
  {include summary.phtml}
</div>
</body> </html>
