 <div class="summryblock">
    <!-- inner wrapper starts here -->
    <div class="innerwrapper">
      <div class="curlyopen"></div>
      <div class="summryblock1">
        <h2>PHP</h2>
        <p>Ut ipsum ultricies ultrices et id sem. Mauris ornare ante ut velit ultrices at condimentum ligula suscipit.</p>
      </div>
      <div class="summryblock2">
        <h2>Javascript & AJAX</h2>
        <p>In sed dui eget augue interdum vestibulum. Quisque a tortor nisi, quis blandit nulla.</p>
      </div>
      <div class="summryblock3">
        <h2>Databázy</h2>
        <p>Ut sapien lacus, mollis facilisis ullamcorper et, vulputate non mauris. Maecenas sollicitudin iaculis cursus. </p>
      </div>
      <div class="curlyclose"></div>
    </div>
    <!-- inner wrapper ends here -->
  </div>