{assign $title 'Users'}
{block #css}
    {include #parent}
    {widget css 'widgets/confirmationdialog.css', 'widgets/datagrid.css'}
    {widget usersCss 'users.css'}
{/block}
{block #js}
    {include #parent}
    {widget js 'datagrid.js'}
{/block}
{block #content}
{widget page}
{/block}
@{block #forms}
{snippet form}
        @{if $edit == true}
        <div id="userEditor" class="ui-corner-all">
            <h2>{_'New user'}</h2>
            @{widget formUser}
        </div>
        @{/if}
    {/snippet}
@{/block}