This is a custom build of Shadowbox version 3.0rc1 that contains only a
subset of the features available. It was compiled using the build tool at
<http://shadowbox-js.com/download.html>. This particular build includes support
for the following:

adapter:  jquery
language: sk
players:  flv, html, iframe, img, swf

The code was compressed using YUI Compressor <http://developer.yahoo.com/yui/compressor/>.
