{assign $templ '../Page/'.$data->content_type.'-'.$data->template.'.phtml'}
{extends $templ}
{assign $title $data->title.' - '.'preview'|translate}
{block #js}
	{include #parent}
	{widget js 'jquery-1.3.2.js', 'jquery-ui-1.7.2.custom.min.js'} {*  'ixedit.js'*}
{/block}
{block #css}
	{include #parent}
	{widget css 'ixedit.css', 'ui-sui.css'} 
{/block}
{block #content}
<script type="text/javascript">
	
	function disableDragging()
	{
		$('.ui-draggable').css('cursor', null);
		//$('.ui-draggable').removeClass('ui-draggable');
		$('.ui-draggable').removeAttr('class');
		//$('*', $('#content-editor')).draggable('destroy');
	}
	
	$(function() {
		//$('*', $('#content-editor')).draggable({ cursor: 'pointer' });
		$('*', $('#page-content')).draggable({ cursor: 'pointer' });
		$('.ui-draggable').css('cursor','pointer');
	});
</script>
<div id="content-editor">
 {include #parent}
 </div>

{/block}