{*
 * @version    		template.phtml 1.0 2009-10-18
 * @param ArrayList $items
 *}

{foreach $items as $item}
        {if $iterator->isFirst()}
                <ul>
        {/if}
        
        {assign $presenter_name $presenter->getName()}
        {assign $request new PresenterRequest($item->url, 'GET', array())}
        {assign $request_name $request->getPresenterName()}
        {if strpos($request_name, $presenter_name) != false} {assign $active 'active'}{else}{assign $active ''}{/if}
        <li class="{$item->label|lower} {$active}"><a href="{$control->getPresenter()->link($item->url)}">{_$item->label}</a>
        {if count($item->items)}
                {include $template->getFile() 'items' => $item->items}
        {/if}
        </li>
        {if $iterator->isLast()}
                </ul>
        {/if}
{/foreach}