<?xml version="1.0" encoding="utf-8" ?>
<manifest xmlns="http://schemas.microsoft.com/wlw/manifest/weblog">
  <weblog>
    <serviceName>Mokuji</serviceName>
    <homepageLinkText>{_'View site'}</homepageLinkText>
    <adminLinkText>{_'Dashboard'}</adminLinkText>
    <adminUrl>
      <![CDATA[{link :Admin:Dashboard:}  ]]>
    </adminUrl>
  </weblog>
 
  <options>
    <clientType>Metaweblog</clientType>
	<supportsGetTags>Yes</supportsGetTags>
	<supportsKeywords>Yes</supportsKeywords>
	<supportsCategories>Yes</supportsCategories>
	<supportsNewCategories>Yes</supportsNewCategories>
	<supportsNewCategoriesInline>Yes</supportsNewCategoriesInline>
	<supportsMultipleCategories>No</supportsMultipleCategories>
	<supportsHierarchicalCategories>Yes</supportsHierarchicalCategories>
	<supportsCommentPolicy>No</supportsCommentPolicy>
	<supportsSlug>Yes</supportsSlug>
	<supportsExcerpt>Yes</supportsExcerpt>
	<supportsPages>No</supportsPages>
	<supportsFileUpload>Yes</supportsFileUpload>
	<supportsPageParent>No</supportsPageParent>
	<supportsPostAsDraft>Yes</supportsPostAsDraft>
	<supportsExtendedEntries>Yes</supportsExtendedEntries>
	<supportsCustomDate>Yes</supportsCustomDate>
	<supportsAuthor>No</supportsAuthor>
	<supportsPassword>No</supportsPassword>
	<supportsEmptyTitles>No</supportsEmptyTitles>
	<supportsEmbeds>Yes</supportsEmbeds>
	<supportsAutoUpdate>Yes</supportsAutoUpdate>
	{*<permalinkFormat><![CDATA[{link :Front:Page:IdView}?id={="{post-id}"}]]></permalinkFormat>*}
  </options>
</manifest>