{*
 * @version            template.phtml 1.0 2009-10-18
 * @param ArrayList $items
 *}
        {foreach $items as $item}
            {if $iterator->isFirst()}
                <ul>
            {/if}
            {assign $active strpos($url, $item->url) !== false}
            <li id="menu-item-{$item->label|lower}" class="{$item->label|lower} {if $active }active{/if} "><a href="{$item->url}">{_$item->label}</a>
            {if count($item->items)}
                {include $template->getFile() 'items' => $item->items}
            {/if}
            </li>
            {if $iterator->isLast()}
                </ul>
            {/if}
        {/foreach}