{extends '../@bluelayout.phtml'}
{block #left}
<!-- text box starts here -->        
                  <div class="text">          <h1>Vivamus dapibus lorem</h1>          
                    <p>Ac lacus lobortis eget suscipit ante imperdiet. Vivamus ac dui enim. Phasellus non ultrices velit. Nullam ultricies velit nec lacus porta a gravida erat lobortis. Mauris nunc sem, porta sit amet sagittis sed, consequat sed augue.
                    </p>        
                  </div>        
                  <!-- text box starts here -->        
                  <!-- text box starts here -->        
                  <div class="text">          <h1>Vivamus dapibus lorem</h1>          
                    <p>Ac lacus lobortis eget suscipit ante imperdiet. Vivamus ac dui enim. Phasellus non ultrices velit. Nullam ultricies velit nec lacus porta a gravida erat lobortis. Mauris nunc sem, porta sit amet sagittis sed, consequat sed augue.
                    </p>        
                  </div>        
                  <!-- text box starts here -->        
                  <!-- text box starts here -->        
                  <div class="text">          <h1>Vivamus dapibus lorem</h1>          
                    <p>Ac lacus lobortis eget suscipit ante imperdiet. Vivamus ac dui enim. Phasellus non ultrices velit. Nullam ultricies velit nec lacus porta a gravida erat lobortis. Mauris nunc sem, porta sit amet sagittis sed, consequat sed augue.
                    </p>        
                  </div>        
                  <!-- text box starts here -->      
{/block}
{block #right}
    <div class="slid">                 
                    <div class="slidheaer">Nam risus tortor, mattis ac sodales at, iaculis eget lorem.
                    </div>          
                    <p>Mauris erat ligula, placerat sed eleifend quis, sodales sit amet elit. Aliquam ac libero quis lectus dictum lobortis eu auctor velit. Praesent ante lectus, sagittis sed lacinia venenatis, semper ut eros. Curabitur egestas urna bibendum nunc cursus euismod.
                    </p>          
                   
                  </div>        
                  </div>      
{/block}